/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.JFrame;
import model.ResponsibleInformation;

/**
 *
 * @author saeed
 */
public class FrmMain extends javax.swing.JFrame {
    
    ResponsibleInformation responsibleInformation;

    public ResponsibleInformation getResponsibleInformation() {
        return responsibleInformation;
    }

    public void setResponsibleInformation(ResponsibleInformation responsibleInformation) {
        this.responsibleInformation = responsibleInformation;
    }

    
    
    
    
    void setRightToLeft(){
        this.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        mainMenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubmenuCertificateRegistration.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubmenuUsersRegistration.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubmenuNationalCardRegistration.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubMenuDisplayLog.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        submenuCertificateIssuance.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        submenuNationalCardIssuance.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        submenuReplicaCertificateIssuance.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        submenuReplicaNationalCardIssuance.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubmenuNationalCardDelivery.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        SubmenuCertificateDelivery.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }
    /**
     * Creates new form Registration
     */
     private void setWindowInMiddle(){
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
     
     private void setFont(){
        Font textFont = new Font("Tahoma", Font.PLAIN, 16);
        Font buttonFont = new Font("Tahoma", Font.BOLD, 14);
        mainMenuBar.setFont(textFont);
        SubmenuCertificateRegistration.setFont(textFont);
        SubmenuUsersRegistration.setFont(textFont);
        SubmenuNationalCardRegistration.setFont(textFont);
        SubMenuDisplayLog.setFont(textFont);
        
        submenuCertificateIssuance.setFont(textFont);
        submenuNationalCardIssuance.setFont(textFont);
        submenuReplicaCertificateIssuance.setFont(textFont);
        submenuReplicaNationalCardIssuance.setFont(textFont);
        SubmenuNationalCardDelivery.setFont(textFont);
        SubmenuCertificateDelivery.setFont(textFont);
        submenuLogout.setFont(textFont);
        
        registrationMenu.setFont(textFont);
        issuanceMenu.setFont(textFont);
        deliveryMenu.setFont(textFont);
        logMenu.setFont(buttonFont);
        SubMenuDisplayLog.setFont(textFont);
        logMenu.setFont(buttonFont);
        issuanceMenu.setFont(buttonFont);
        registrationMenu.setFont(buttonFont);
        deliveryMenu.setFont(buttonFont);
        exitMenu.setFont(buttonFont);
     }
    public FrmMain() {
        initComponents();
        setRightToLeft();
        setWindowInMiddle();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setFont();
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        mainMenuBar = new javax.swing.JMenuBar();
        registrationMenu = new javax.swing.JMenu();
        SubmenuUsersRegistration = new javax.swing.JMenuItem();
        SubmenuNationalCardRegistration = new javax.swing.JMenuItem();
        SubmenuCertificateRegistration = new javax.swing.JMenuItem();
        issuanceMenu = new javax.swing.JMenu();
        submenuCertificateIssuance = new javax.swing.JMenuItem();
        submenuNationalCardIssuance = new javax.swing.JMenuItem();
        submenuReplicaCertificateIssuance = new javax.swing.JMenuItem();
        submenuReplicaNationalCardIssuance = new javax.swing.JMenuItem();
        deliveryMenu = new javax.swing.JMenu();
        SubmenuCertificateDelivery = new javax.swing.JMenuItem();
        SubmenuNationalCardDelivery = new javax.swing.JMenuItem();
        logMenu = new javax.swing.JMenu();
        SubMenuDisplayLog = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();
        submenuLogout = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem10.setText("jMenuItem10");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu8.setText("jMenu8");

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        registrationMenu.setText("ثبت");

        SubmenuUsersRegistration.setText("ثبت اطلاعات کارمندان");
        SubmenuUsersRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuUsersRegistrationActionPerformed(evt);
            }
        });
        registrationMenu.add(SubmenuUsersRegistration);

        SubmenuNationalCardRegistration.setText("ثبت اطلاعات کارت ملی");
        SubmenuNationalCardRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuNationalCardRegistrationActionPerformed(evt);
            }
        });
        registrationMenu.add(SubmenuNationalCardRegistration);

        SubmenuCertificateRegistration.setText("ثبت اطلاعات شناسنامه");
        SubmenuCertificateRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuCertificateRegistrationActionPerformed(evt);
            }
        });
        registrationMenu.add(SubmenuCertificateRegistration);

        mainMenuBar.add(registrationMenu);

        issuanceMenu.setText("صدور");

        submenuCertificateIssuance.setText("صدور شناسنامه");
        submenuCertificateIssuance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCertificateIssuanceActionPerformed(evt);
            }
        });
        issuanceMenu.add(submenuCertificateIssuance);

        submenuNationalCardIssuance.setText("صدور کارت ملی");
        submenuNationalCardIssuance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuNationalCardIssuanceActionPerformed(evt);
            }
        });
        issuanceMenu.add(submenuNationalCardIssuance);

        submenuReplicaCertificateIssuance.setText("صدور المثنی شناسنامه");
        submenuReplicaCertificateIssuance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuReplicaCertificateIssuanceActionPerformed(evt);
            }
        });
        issuanceMenu.add(submenuReplicaCertificateIssuance);

        submenuReplicaNationalCardIssuance.setText("صدور المثنی کارت ملی");
        submenuReplicaNationalCardIssuance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuReplicaNationalCardIssuanceActionPerformed(evt);
            }
        });
        issuanceMenu.add(submenuReplicaNationalCardIssuance);

        mainMenuBar.add(issuanceMenu);

        deliveryMenu.setText("تحویل");

        SubmenuCertificateDelivery.setText("تحویل  شناسنامه");
        SubmenuCertificateDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuCertificateDeliveryActionPerformed(evt);
            }
        });
        deliveryMenu.add(SubmenuCertificateDelivery);

        SubmenuNationalCardDelivery.setText("تحویل کارت ملی");
        SubmenuNationalCardDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuNationalCardDeliveryActionPerformed(evt);
            }
        });
        deliveryMenu.add(SubmenuNationalCardDelivery);

        mainMenuBar.add(deliveryMenu);

        logMenu.setText("مشاهده اطلاعات");

        SubMenuDisplayLog.setText("نمایش");
        SubMenuDisplayLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuDisplayLogActionPerformed(evt);
            }
        });
        logMenu.add(SubMenuDisplayLog);

        mainMenuBar.add(logMenu);

        exitMenu.setText("خروج");

        submenuLogout.setText("خروج");
        submenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuLogoutActionPerformed(evt);
            }
        });
        exitMenu.add(submenuLogout);

        mainMenuBar.add(exitMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuNationalCardIssuanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuNationalCardIssuanceActionPerformed
        // TODO add your handling code here:
        new FrmIssuanceNid(this, false).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_submenuNationalCardIssuanceActionPerformed

    private void submenuReplicaNationalCardIssuanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuReplicaNationalCardIssuanceActionPerformed
        // TODO add your handling code here:
        new FrmIssuanceNid(this, true).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_submenuReplicaNationalCardIssuanceActionPerformed

    private void SubmenuNationalCardDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuNationalCardDeliveryActionPerformed
        // TODO add your handling code here:
        new FrmDeliverNid(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubmenuNationalCardDeliveryActionPerformed

    private void SubmenuCertificateRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuCertificateRegistrationActionPerformed
        // TODO add your handling code here:
        new FrmRegistrationBirthCertificate(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubmenuCertificateRegistrationActionPerformed

    private void SubMenuDisplayLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuDisplayLogActionPerformed
        // TODO add your handling code here:
        new FrmDisplayLog(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubMenuDisplayLogActionPerformed

    private void submenuCertificateIssuanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCertificateIssuanceActionPerformed
        // TODO add your handling code here:
        new FrmIssuanceCertificate(this, false).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_submenuCertificateIssuanceActionPerformed

    private void submenuReplicaCertificateIssuanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuReplicaCertificateIssuanceActionPerformed
        // TODO add your handling code here:
        new FrmIssuanceCertificate(this, true).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_submenuReplicaCertificateIssuanceActionPerformed

    private void SubmenuNationalCardRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuNationalCardRegistrationActionPerformed
        // TODO add your handling code here:
        new FrmRegistrationNationalCardInformation(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubmenuNationalCardRegistrationActionPerformed

    private void SubmenuUsersRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuUsersRegistrationActionPerformed
        // TODO add your handling code here:
        new FrmUsers(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubmenuUsersRegistrationActionPerformed

    private void SubmenuCertificateDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuCertificateDeliveryActionPerformed
        // TODO add your handling code here:
        new FrmDeliverCertificate(this).setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_SubmenuCertificateDeliveryActionPerformed

    private void submenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuLogoutActionPerformed
        // TODO add your handling code here:
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SubMenuDisplayLog;
    private javax.swing.JMenuItem SubmenuCertificateDelivery;
    private javax.swing.JMenuItem SubmenuCertificateRegistration;
    private javax.swing.JMenuItem SubmenuNationalCardDelivery;
    private javax.swing.JMenuItem SubmenuNationalCardRegistration;
    private javax.swing.JMenuItem SubmenuUsersRegistration;
    private javax.swing.JMenu deliveryMenu;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenu issuanceMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu logMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu registrationMenu;
    private javax.swing.JMenuItem submenuCertificateIssuance;
    private javax.swing.JMenuItem submenuLogout;
    private javax.swing.JMenuItem submenuNationalCardIssuance;
    private javax.swing.JMenuItem submenuReplicaCertificateIssuance;
    private javax.swing.JMenuItem submenuReplicaNationalCardIssuance;
    // End of variables declaration//GEN-END:variables

    

    
}
